swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6><textarea><a title="</textarea><img src="invalid.jpg" onerror="alert('Image loaded!')">>">
  version: production
