swagger: '2.0'
info:
  title: XSS test
  description: |
  <form action="/upload" method="post" enctype="multipart/form-data">
                <input type="file" name="file" id="fileUpload">
                <input type="submit" value="Upload File">
            </form>
  
  version: production
