swagger: '2.0'
info:
  title: XSS test
  description: <a href="https://www.reddit.com/r/QuotesPorn/comments/12sje6f/social_media_made_yall_way_too_comfortable_with">Click Me</a>
  <img src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHVramtqbnN3Ym8wbHFvcnM2ZjN2ZHAxNWR4OHFqdndnMzd3djFwNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Vu5UbNpjpqfMq2UFg0/giphy.webp" onload="alert('Image loaded!')">>">
  version: production
