swagger: '2.0'
info:
  title: XSS test
  description: <a href="https://www.reddit.com/r/QuotesPorn/comments/12sje6f/social_media_made_yall_way_too_comfortable_with">Click Me</a> 
  version: production
